const translations = {
  zh: {
    brand_title: "南十字星 · 网站构建",
    brand_sub: "让你的业务被看见",
    nav_work: "作品",
    nav_services: "服务",
    nav_pricing: "价格",
    nav_contact: "联系",
    hero_tag: "你在找“能落地”的网站设计师",
    hero_title: "我把你的价值，用网站变成客户的决定。",
    hero_lede: "专注个人品牌与小团队的高转化官网。快速、清晰、可维护。",
    hero_cta_primary: "查看价格",
    hero_cta_secondary: "查看作品",
    metric_sites: "已交付网站",
    metric_days: "天交付",
    metric_focus: "聚焦结果",
    hero_card_title: "项目进行中",
    hero_card_item1: "品牌梳理",
    hero_card_item2: "结构与文案",
    hero_card_item3: "视觉与开发",
    hero_card_title2: "交付清单",
    hero_card_list1: "主页 + 关键落地页",
    hero_card_list2: "响应式 + SEO 基础",
    hero_card_list3: "可复制的内容模板",
    services_title: "为你做的不是“网页”，而是“成交路径”",
    service1_title: "定位与策略",
    service1_desc: "抓住你的差异点，把故事变成首页 5 秒能理解的价值。",
    service2_title: "视觉与体验",
    service2_desc: "大胆但克制的视觉系统，确保在手机和电脑上都专业。",
    service3_title: "上线与迭代",
    service3_desc: "交付可维护文件，后续扩展有章可循。",
    work_title: "网站样例",
    work_desc: "下面是一些已完成的网站，适合品牌、社群、活动或产品展示。",
    work1_desc: "音乐品牌视觉与产品聚焦。",
    work2_desc: "游戏集合展示，轻量动效。",
    work3_desc: "讲清楚个人价值与项目。",
    work4_desc: "面向用户的健康服务介绍。",
    work5_desc: "以场景塑造产品价值。",
    work6_desc: "强调故事感与产品层次。",
    process_title: "合作流程",
    process_desc: "我会快速落地，同时保证每一步都清晰可控。",
    process1_title: "梳理目标",
    process1_desc: "30-60 分钟访谈，明确你要吸引谁。",
    process2_title: "内容与结构",
    process2_desc: "给出框架与文案方向，先解决“说清楚”。",
    process3_title: "视觉与开发",
    process3_desc: "在 7-14 天内完成设计 + 前端交付。",
    process4_title: "上线与复盘",
    process4_desc: "上线后提供一轮优化建议。",
    pricing_title: "价格方案",
    pricing_desc: "选择适合你的投入强度，所有方案都可定制。",
    price1_title: "启动版",
    price1_value: "A$999 + GST",
    price1_item1: "1-3 页核心内容",
    price1_item2: "视觉系统 + 响应式",
    price1_item3: "基础 SEO",
    price1_item4: "7 天交付",
    price2_title: "标准版",
    price2_value: "咨询报价",
    price2_item1: "5-8 页 + 1 个落地页",
    price2_item2: "品牌视觉与故事化文案",
    price2_item3: "动效与交互细节",
    price2_item4: "10-14 天交付",
    price3_title: "旗舰版",
    price3_value: "咨询报价",
    price3_item1: "10+ 页 + 多语言支持",
    price3_item2: "品牌摄影与插画方向",
    price3_item3: "定制组件与扩展",
    price3_item4: "14-21 天交付",
    price_badge: "最受欢迎",
    price_cta: "咨询方案",
    cta_title: "准备好让你的客户更快理解你了吗？",
    cta_desc: "发我一句话，24 小时内给你方案建议。",
    cta_email: "发送邮件",
    cta_chat: "聊聊项目",
    footer_title: "南十字星 · 网站构建",
    footer_sub: "作品集中展示于此页面",
    footer_note: "可开票 · 远程合作"
  },
  en: {
    brand_title: "Southern Cross · Website Studio",
    brand_sub: "Make your business easy to choose",
    nav_work: "Work",
    nav_services: "Services",
    nav_pricing: "Pricing",
    nav_contact: "Contact",
    hero_tag: "You need a website builder who ships",
    hero_title: "I turn your value into a website that wins decisions.",
    hero_lede: "High-conversion sites for personal brands and small teams. Fast, clear, maintainable.",
    hero_cta_primary: "See Pricing",
    hero_cta_secondary: "View Work",
    metric_sites: "Sites delivered",
    metric_days: "Days to ship",
    metric_focus: "Result focused",
    hero_card_title: "Project Status",
    hero_card_item1: "Brand strategy",
    hero_card_item2: "Structure & copy",
    hero_card_item3: "Design & build",
    hero_card_title2: "Deliverables",
    hero_card_list1: "Homepage + key landing",
    hero_card_list2: "Responsive + basic SEO",
    hero_card_list3: "Reusable content templates",
    services_title: "Not just pages. A conversion path.",
    service1_title: "Positioning",
    service1_desc: "Crystallize your difference into a 5-second message.",
    service2_title: "Visual & UX",
    service2_desc: "Bold yet precise design that looks great everywhere.",
    service3_title: "Launch & iterate",
    service3_desc: "Clean handoff with a scalable structure.",
    work_title: "Selected Work",
    work_desc: "A few shipped websites for brands, communities, and campaigns.",
    work1_desc: "Music brand visual and product focus.",
    work2_desc: "Game showcase with light interactions.",
    work3_desc: "A personal brand, clear and minimal.",
    work4_desc: "Health service intro for credibility.",
    work5_desc: "Scene-led storytelling for product value.",
    work6_desc: "Story-first brand experience.",
    process_title: "How We Work",
    process_desc: "Fast delivery with clarity at every step.",
    process1_title: "Define goals",
    process1_desc: "30-60 min call to map your audience.",
    process2_title: "Content & structure",
    process2_desc: "Outline the story before visuals.",
    process3_title: "Design & build",
    process3_desc: "Design + build in 7-14 days.",
    process4_title: "Launch & review",
    process4_desc: "A round of post-launch optimization.",
    pricing_title: "Pricing Plans",
    pricing_desc: "Pick the level that matches your momentum. All plans are customizable.",
    price1_title: "Starter",
    price1_value: "A$999 + GST",
    price1_item1: "1-3 essential pages",
    price1_item2: "Visual system + responsive",
    price1_item3: "Basic SEO",
    price1_item4: "7-day delivery",
    price2_title: "Standard",
    price2_value: "Custom quote",
    price2_item1: "5-8 pages + landing",
    price2_item2: "Brand narrative copy",
    price2_item3: "Animations & interactions",
    price2_item4: "10-14 days delivery",
    price3_title: "Signature",
    price3_value: "Custom quote",
    price3_item1: "10+ pages + multi-language",
    price3_item2: "Photo & illustration direction",
    price3_item3: "Custom components",
    price3_item4: "14-21 days delivery",
    price_badge: "Most Popular",
    price_cta: "Get a Quote",
    cta_title: "Ready to make your value obvious?",
    cta_desc: "Send one message and get a plan within 24 hours.",
    cta_email: "Email Me",
    cta_chat: "Discuss Project",
    footer_title: "Southern Cross · Website Studio",
    footer_sub: "Portfolio curated on this page",
    footer_note: "Remote friendly · Invoicing available"
  }
};

const langToggle = document.getElementById("langToggle");
let currentLang = localStorage.getItem("ns_lang") || "zh";

function applyTranslations(lang) {
  const dict = translations[lang];
  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.getAttribute("data-i18n");
    if (dict[key]) {
      el.textContent = dict[key];
    }
  });
  langToggle.textContent = lang === "zh" ? "EN" : "中文";
}

langToggle.addEventListener("click", () => {
  currentLang = currentLang === "zh" ? "en" : "zh";
  localStorage.setItem("ns_lang", currentLang);
  applyTranslations(currentLang);
});

applyTranslations(currentLang);
